name: check-quality

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Norminette
        run: |
          norminette . > norm.log || true
          cat norm.log

          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
        
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re
        
  Macos:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          brew update
          brew install coreutils

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Norminette
        run: |
          norminette . > norm.log || true
          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
      
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re
        
  Fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    continue-on-error: true 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf install -ycoreutils make gcc python3-pip python3-devel

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install norminette

      - name: Run Norminette
        run: |
          python3 -m norminette . > norm.log || true
          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
      
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re
        
  Alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          apk update
          apk add build-base coreutils python3 py3-pip

      - name: Install Norminette
        run: |
          python3 -m venv /opt/venv
          /opt/venv/bin/pip install --upgrade pip
          /opt/venv/bin/pip install norminette
          ln -s /opt/venv/bin/norminette /usr/bin/norminette

      - name: Run Norminette
        run: |
          norminette . > norm.log || true
          if grep "Error:" norm.log | grep -v -E "Global variable|WRONG_SCOPE_VAR" > filtered_errors.log; then
            echo "❌ Norminette Errors Found:"
            cat filtered_errors.log
            exit 1
          else
            echo "✅ Norminette Success"
          fi
      
      - name: Compilation
        run: |
          make
          make clean
          make fclean
          make re
